import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Monitor from '../components/Monitor';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vienna Metro Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Monitor />
    </div>
  );
}
